#!/usr/bin/env python3
"""Generate the API-key catalog and .env.template from tool configs + metadata.

Authoritative key names come from each tool's required_api_keys /
optional_api_keys arrays. Domain, registration link, purpose, and the
without-it note come from src/tooluniverse/data/api_key_metadata.json.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
DATA = REPO / "src" / "tooluniverse" / "data"
METADATA = DATA / "api_key_metadata.json"
CATALOG = DATA / "api_keys_catalog.json"
ENV_TEMPLATE = REPO / ".env.template"
_SKIP = {"api_key_metadata.json", "api_keys_catalog.json"}

DOMAIN_ORDER = [
    "Genomics & Variants",
    "Drugs & Chemistry",
    "Proteins & Structure",
    "Literature & Patents",
    "Clinical & Safety",
    "Models & Infrastructure",
]


def discover_keys() -> dict:
    """Scan tool configs for declared API-key env-var names."""
    found: dict = {}
    for path in sorted(DATA.glob("*.json")):
        if path.name in _SKIP:
            continue
        try:
            doc = json.loads(path.read_text())
        except (json.JSONDecodeError, OSError):
            continue
        tools = doc if isinstance(doc, list) else [doc]
        for tool in tools:
            if not isinstance(tool, dict):
                continue
            for name in tool.get("required_api_keys") or []:
                entry = found.setdefault(name, {"requirement": "optional", "used_by": set()})
                entry["requirement"] = "required"
                entry["used_by"].add(path.name)
            for name in tool.get("optional_api_keys") or []:
                entry = found.setdefault(name, {"requirement": "optional", "used_by": set()})
                entry["used_by"].add(path.name)
    return found


def build_catalog(found: dict, metadata: dict):
    """Merge discovered keys with metadata. Returns (catalog, missing, unused)."""
    catalog, missing = [], []
    for name in sorted(found):
        meta = metadata.get(name)
        if meta is None:
            missing.append(name)
            continue
        catalog.append({
            "name": name,
            "requirement": found[name]["requirement"],
            "type": meta.get("type", "secret"),
            "domain": meta.get("domain", "Other"),
            "register_url": meta["register_url"],
            "purpose": meta["purpose"],
            "without": meta["without"],
            "used_by": sorted(found[name]["used_by"]),
        })
    unused = sorted(set(metadata) - set(found))
    return catalog, missing, unused


def render_env_template(catalog: list) -> str:
    lines = [
        "# API Keys for ToolUniverse",
        "# AUTO-GENERATED by scripts/gen_api_key_catalog.py - DO NOT EDIT BY HAND.",
        "# Edit links/descriptions in src/tooluniverse/data/api_key_metadata.json.",
        "# Copy to .env or ~/.tooluniverse/.env and fill in the keys you need.",
        "",
    ]
    seen = dict.fromkeys(e["domain"] for e in catalog)
    domains = [d for d in DOMAIN_ORDER if d in seen] + [d for d in seen if d not in DOMAIN_ORDER]
    for domain in domains:
        items = [e for e in catalog if e["domain"] == domain]
        if not items:
            continue
        lines += [f"# === {domain} ===", ""]
        for e in items:
            lines += [
                f"# {e['name']} ({e['requirement']}) — {e['purpose']} ({e['register_url']})",
                f"# Without: {e['without']}",
                f"{e['name']}=",
                "",
            ]
    return "\n".join(lines).rstrip() + "\n"


def main(argv=None) -> int:
    metadata = json.loads(METADATA.read_text())
    found = discover_keys()
    catalog, missing, unused = build_catalog(found, metadata)
    for name in unused:
        print(f"warning: metadata entry '{name}' is not used by any tool config", file=sys.stderr)
    if missing:
        for name in missing:
            print(f"error: tool config key '{name}' has no entry in {METADATA.name}", file=sys.stderr)
        return 1
    CATALOG.write_text(json.dumps(catalog, indent=2) + "\n")
    ENV_TEMPLATE.write_text(render_env_template(catalog))
    print(f"Wrote {len(catalog)} keys to {CATALOG.relative_to(REPO)} and {ENV_TEMPLATE.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
