#!/usr/bin/env python3
"""Generate the API-key catalog and .env.template from tool configs + metadata.

Authoritative key names come from each tool's required_api_keys /
optional_api_keys arrays. Registration links, descriptions, and the
secret/endpoint type come from src/tooluniverse/data/api_key_metadata.json.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
DATA = REPO / "src" / "tooluniverse" / "data"
METADATA = DATA / "api_key_metadata.json"
CATALOG = DATA / "api_keys_catalog.json"
ENV_TEMPLATE = REPO / ".env.template"
_SKIP = {"api_key_metadata.json", "api_keys_catalog.json"}


def discover_keys() -> dict:
    """Scan tool configs for declared API-key env-var names."""
    found: dict = {}
    for path in sorted(DATA.glob("*.json")):
        if path.name in _SKIP:
            continue
        try:
            doc = json.loads(path.read_text())
        except (json.JSONDecodeError, OSError):
            continue
        tools = doc if isinstance(doc, list) else [doc]
        for tool in tools:
            if not isinstance(tool, dict):
                continue
            for name in tool.get("required_api_keys") or []:
                entry = found.setdefault(name, {"requirement": "optional", "used_by": set()})
                entry["requirement"] = "required"
                entry["used_by"].add(path.name)
            for name in tool.get("optional_api_keys") or []:
                entry = found.setdefault(name, {"requirement": "optional", "used_by": set()})
                entry["used_by"].add(path.name)
    return found


def build_catalog(found: dict, metadata: dict):
    """Merge discovered keys with metadata. Returns (catalog, missing, unused)."""
    catalog, missing = [], []
    for name in sorted(found):
        meta = metadata.get(name)
        if meta is None:
            missing.append(name)
            continue
        catalog.append({
            "name": name,
            "requirement": found[name]["requirement"],
            "type": meta.get("type", "secret"),
            "register_url": meta["register_url"],
            "description": meta["description"],
            "used_by": sorted(found[name]["used_by"]),
        })
    unused = sorted(set(metadata) - set(found))
    return catalog, missing, unused


def render_env_template(catalog: list) -> str:
    lines = [
        "# API Keys for ToolUniverse",
        "# AUTO-GENERATED by scripts/gen_api_key_catalog.py - DO NOT EDIT BY HAND.",
        "# Edit links/descriptions in src/tooluniverse/data/api_key_metadata.json.",
        "# Copy to .env or ~/.tooluniverse/.env and fill in your keys.",
        "",
    ]
    secrets = [e for e in catalog if e["type"] == "secret"]
    for req, title in (
        ("required", "Required API Keys (tool will not work without these)"),
        ("optional", "Optional API Keys (improve rate limits or unlock data)"),
    ):
        block = [e for e in secrets if e["requirement"] == req]
        if not block:
            continue
        lines += [f"# --- {title} ---", ""]
        for e in block:
            lines += [f"# {e['name']}: {e['description']} ({e['register_url']})", f"{e['name']}=", ""]
    endpoints = [e for e in catalog if e["type"] == "endpoint"]
    if endpoints:
        lines += ["# --- Service Endpoints (advanced; self-hosted MCP servers) ---", ""]
        for e in endpoints:
            lines += [f"# {e['name']}: {e['description']} ({e['register_url']})", f"{e['name']}=", ""]
    return "\n".join(lines).rstrip() + "\n"


def main(argv=None) -> int:
    metadata = json.loads(METADATA.read_text())
    found = discover_keys()
    catalog, missing, unused = build_catalog(found, metadata)
    for name in unused:
        print(f"warning: metadata entry '{name}' is not used by any tool config", file=sys.stderr)
    if missing:
        for name in missing:
            print(f"error: tool config key '{name}' has no entry in {METADATA.name}", file=sys.stderr)
        return 1
    CATALOG.write_text(json.dumps(catalog, indent=2) + "\n")
    ENV_TEMPLATE.write_text(render_env_template(catalog))
    print(f"Wrote {len(catalog)} keys to {CATALOG.relative_to(REPO)} and {ENV_TEMPLATE.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
